### ISSUE TITLE
problems integrating stracker

### ISSUE THREAD

**Issue by port22** [cj123/assetto-server-manager#539]
Hi guys,
I really have a hard time understanding how it's designed to integrate stracker.
Currently, I set Server->Options to this:
```
UDP Plugin Local Port: 11600
UDP Plugin Address: 127.0.0.1:12600
```
Now I understand, that server-manager will choose random free ports on which acServer then will listen on and proxy traffic either ways. While no acServer is started, `netstat` shows:
```
tcp        0      0 127.0.0.11:41795        0.0.0.0:*               LISTEN      0          922898     -                   
udp        0      0 127.0.0.11:33858        0.0.0.0:*                           0          922897     -                   
```
Which I suppose, are the mentioned random proxy ports.

Now I start a Custom Race, and for example it generates these values in server_cfg.ini:
```
UDP_PLUGIN_LOCAL_PORT=54853
UDP_PLUGIN_ADDRESS=127.0.0.1:54079
```
And netstat now shows:
```
udp6       0      0 :::54853                :::*                                1000       923946     24/acServer         
```
So far, so good. Now, I will configure stracker. Default is this:
```
[ACPLUGIN]
; proxy the AC server protocol on these ports, so multiple plugins may be chained (this is equivalent to UDP_PLUGIN_LOCAL_PORT in server_cfg.ini)
proxyPluginLocalPort = -1
; proxy the AC server protocol on these ports, so multiple plugins may be chained (this is equivalent to UDP_PLUGIN_ADDRESS in server_cfg.ini)
proxyPluginPort = -1
; udp port the plugins receives from. -1 means to use the AC servers setting UDP_PLUGIN_ADDRESS
rcvPort = -1
; udp port the plugins sends to. -1 means to use the AC servers setting UDP_PLUGIN_LOCAL_PORT
sendPort = -1
```
But as the `config.yml` tells,
```
  # - rcvPort must equal the port from the UDP Plugin Address
  # - sendPort must equal the value of the UDP Plugin Local Port
```
I have to change the following stracker config values to:
```
rcvPort = 127.0.0.1:12600
sendPort = 11600
```
Now I start stracker manually:
```
stracker[WARN ]: Error reading ACPLUGIN/rcvPort. Using default.
```
sTracker changed the customized values in stracker.ini back to `-1` because of an unknown reason.

`stracker.log`:
```
{2019-10-06 12:07:23}: stracker[INFO ]: Using plugin configuration rcvport=54079 sendport=11600 proxy=(None/None)
{2019-10-06 12:07:23}: stracker[ERROR]: Caught exception in server loop:
{2019-10-06 12:07:23}: stracker[ERROR]: Traceback (most recent call last):
  File "stracker/stracker_lib/ac_monitor.py", line 1914, in run
  File "stracker/stracker_lib/stracker_udp_plugin.py", line 193, in __init__
  File "stracker/externals/acplugins4python/ac_server_plugin.py", line 115, in __init__
  File "stracker/externals/acplugins4python/ac_server_plugin.py", line 145, in openSocket
OSError: [Errno 98] Address already in use
```
Then it complains that a not mentioned address is already in use. 

By killing acServer and then starting stracker manually, I can see it now binds to 54079, but I don't see a reason why it didn't work before, because it was not visibly in use, at least by netstat. 
Do I change the rcvport to something random, stracker then start, which proofs it's the rcvport causing the bind problem.

Do I understand something basically wrong here?
Thanks for any help!

**Comment by port22** [comment]
Oh god, I can't believe I just found out a minute after posting this, that rcvPort is just the port, not the address
```
rcvPort = 12600
```
sorry for spam -.-

**Comment by port22** [comment]
Anyway, running stracker from the `run_on_start` config doesn't work:
```
time="2019-10-06T12:31:58Z" level=error msg="Could not run extra command: /home/assetto/server-manager/assetto/plugins/stracker/stracker_linux_x86/stracker --stracker_ini /storage/stracker.ini, err: fork/exec /home/assetto/server-manager/assetto/plugins/stracker/stracker_linux_x86/stracker: no such file or directory"
```
But it's all there.
```
assetto@9bd02a8eb5fe:~/server-manager$ ls -al /home/assetto/server-manager/assetto/plugins/stracker/stracker_linux_x86/stracker /storage/stracker.ini
-rwxr-xr-x. 1 assetto assetto 2297689 Oct  5 18:21 /home/assetto/server-manager/assetto/plugins/stracker/stracker_linux_x86/stracker
-rw-r--r--. 1 assetto assetto    9254 Oct  6 12:25 /storage/stracker.ini
```
